package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/Interceptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-macosx-x86_64/jdk8u25/1514/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, September 17, 2014 4:58:16 PM PDT
*/


/**
   * All Portable Interceptors implement Interceptor.
   */
public interface Interceptor extends InterceptorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interceptor
